#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    dict_pair = {}
    for i in ar:
        if i in dict_pair:
            dict_pair[i] += 1
        else:
            dict_pair [i] = 1
    ans = 0
    for value in dict_pair.values():
        ans += value//2
    return ans
    
    if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
